### ISSUE TITLE
Behaves oddly with xdist

### ISSUE THREAD

**Issue by xmo-odoo** [ratson/pytest-notifier#10]
xdist is useful even locally in order to distribute tests amongst multiple cores (especially these days as even the most basic laptops have 4 logical cores, and AMD is apparently planning for 16-logical APUs).

However when using xdist and pytest-notify at the same time it seems like pytest-notify generates a notification per worker when the worker is killed, and no global notification?

So e.g. if I'm running 3 tests on 2 workers and get
```
[gw1] [ 33%] FAILED test_1
[gw0] [ 66%] PASSED test_0 
[gw0] [100%] FAILED test_2
```
I'm getting one report of 100% failure (1/1) then a bit later when worker 0 finishes a second report of 50% failure (1/2). And so far as I can see no notification of 66% (2/3) failure for the overall job (though it could be that there's a race condition and worker 0's notification overwrites the global one).

**Comment by bullfest** [comment]
I don't quite get the same problem you have @xmo-odoo, but I suspect that your issue is solved by my PR above as well :smiley:. It would be great if you could try it out!
